# fly.toml app configuration file generated for apiautomationassistant on 2025-04-01T16:12:42+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-automation-app"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "apiautomation_data"
  destination = "/app/data"
